name: Test kdestin/evaluate
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_AI_SUBSCRIPTION_ID }}
      - uses: kdestin/evaluate@main
        with:
          data: ${GITHUB_WORKSPACE}/data.jsonl
          ai_model_configuration: |
            {
              "type": "azure_openai",
              "azure_deployment": "gpt-35-turbo",
              "api_key": "${{ secrets.AZURE_OPENAI_API_KEY}}",
              "azure_endpoint": "${{ secrets.AZURE_OPENAI_ENDPOINT_NAME }}"
            }
          evaluators: |
            {
              "bleu": "BleuScoreEvaluator",
              "content_safety": "ContentSafetyEvaluator"
            }
          azure_ai_project: |
            {
              "subscription_id": "${{ secrets.AZURE_AI_SUBSCRIPTION_ID }}",
              "resource_group_name": "${{ secrets.AZURE_AI_RESOURCE_GROUP_NAME }}",
              "project_name": "${{ secrets.AZURE_AI_PROJECT_NAME }}"
            }
          output_path: ${GITHUB_WORKSPACE}/results.jsonl
      - run: cat ${GITHUB_WORKSPACE}/results.jsonl >> $GITHUB_STEP_SUMMARY
